#' Ripley K score
#'
#' Get a single value to summary the results from ripley_k
#'
#' @param df Data frame generated by ripley_k
#' @param method Method to use to get the statistic. So far, only "sum"
#' (sum of differences between k and T) and sumabs (sum of absolute differences between k and T)
#' are valid
#'
#' @export
#'
ripley_k_score <- function(df, method = "sum") {
    if (!is.data.frame(df)) {
        stop("df must be a data frame")
    }
    if (sum(c("t", "K") %in% colnames(df)) != 2) {
        stop("Invalid data frame")
    }

    if (method == "sum") {
        out <- sum(df$K - df$t)
    } else if (method == "sumabs") {
        out <- sum(abs(df$K - df$t))
    } else {
        stop("Invalid method ", method)
    }
    out
}
